services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=sistemanotas'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
      
volumes:
  postgres:
